### ISSUE TITLE
Pushing to Github via terminal Doesn't Support Password Auth Anymore

### ISSUE THREAD

**Issue by renweview** [pplonski/my_ml_service#29]
```
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/pplonski/my_ml_service.git/'
(base) Ren-iMac:my_ml_service renaisawahed$ git remote add origin https://github.com/teafirst/my_ml_service.git
fatal: remote origin already exists.
(base) Ren-iMac:my_ml_service renaisawahed$ git remote add origin https://github.com/pplonski/my_ml_service.git
fatal: remote origin already exists.
(base) Ren-iMac:my_ml_service renaisawahed$ git branch -M main
(base) Ren-iMac:my_ml_service renaisawahed$ git push -u origin main
Username for 'https://github.com': teafirst
Password for 'https://teafirst@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/pplonski/my_ml_service.git/'
```
Hello! I'm following your tutorial from deploymachinelearning.com and where it says to "Add source files to the repository" from terminal has been giving the error shown above. 
I went to the Github docs site and eventually sorted it out by importing all the files into my cloned repo through Github with the 'import' function, but I was wondering if you had a work around for this error on terminal?

**Comment by pplonski** [comment]
Hi @renrenwa!

Two issues:
### 1. Auth with SSH
```
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
```
The first two lines tell you that you can't authenticate with a password anymore to GitHub. Please set SSH keys. https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

### 2. Create your repo
```
fatal: Authentication failed for 'https://github.com/pplonski/my_ml_service.git/'
```
Please create a new repository in your GitHub account and replace all occurrences `pplonski/my_ml_service` with your repo. I would advise you not to clone my repo. Please start with an empty repository and follow the tutorial steps to fill the repo with code :)


Please let me know if it works for you.
