### ISSUE TITLE
{'status': 'Error', 'message': "'LabelEncoder' object is not subscriptable"}

### ISSUE THREAD

**Issue by farahabdelsalam** [pplonski/my_ml_service#3]
Hi I get this error when I run the tests part, any idea what the problem could be?
Thanks

**Comment by pplonski** [comment]
Hmmm, it looks like some problem with scikit learn encoder. Can you give me more details how you run tests, have you made any changes to the code?

**Comment by farahabdelsalam** [comment]
I'm using a decision tree classifier, my ml is exactly the same with the difference of the label encoding fields. The input is different in the test file only, and the postprocessing method only has return {status: OK} . I'm now getting an assertation error at self.assertEqual('OK', response['status'])
Thanks
<img width="419" alt="Annotation 2020-06-19 194202" src="https://user-images.githubusercontent.com/47149564/85164773-232fd600-b265-11ea-9c39-d9d4bde96928.png">
<img width="389" alt="Annotation 2020-06-19 194306" src="https://user-images.githubusercontent.com/47149564/85164837-35aa0f80-b265-11ea-82fc-cfe49bc71e07.png">

**Comment by pplonski** [comment]
I'm closing the issue as it is not related to this repo.

In `postprocessing`, you are returning only `"status": "OK"` - you overwrite your predictions. Please look closely how it is done here: https://github.com/pplonski/my_ml_service/blob/master/backend/server/apps/ml/income_classifier/random_forest.py
